<?php

return [
    'tools' => [
        [
            'name' => 'list_organizations',
            'class' => \App\Mcp\Tools\Organization\ListOrganizationsTool::class,
            'description' => 'List all organizations in your ServerAvatar account',
            'usage' => 'listOrganizations()',
            'icon' => '🏢',
        ],
        [
            'name' => 'list_servers',
            'class' => \App\Mcp\Tools\Server\ListServersTool::class,
            'description' => 'List all servers in your ServerAvatar account',
            'usage' => 'listServers(organizationId)',
            'icon' => '🖥️',
        ],
        [
            'name' => 'get_server',
            'class' => \App\Mcp\Tools\Server\GetServerTool::class,
            'description' => 'Get details of a specific server',
            'usage' => 'getServer(organizationId, serverId)',
            'icon' => '📊',
        ],
        [
            'name' => 'get_server_usage',
            'class' => \App\Mcp\Tools\Server\GetServerUsageTool::class,
            'description' => 'Get CPU, Memory, and Disk usage for a server',
            'usage' => 'getServerUsage(organizationId, serverId)',
            'icon' => '📈',
        ],
        [
            'name' => 'view_server_logs',
            'class' => \App\Mcp\Tools\Server\ViewServerLogsTool::class,
            'description' => 'View server logs',
            'usage' => 'viewServerLogs(organizationId, serverId)',
            'icon' => '📋',
        ],
        [
            'name' => 'get_server_processes',
            'class' => \App\Mcp\Tools\Server\GetServerProcessesTool::class,
            'description' => 'Get list of running processes on a server',
            'usage' => 'getServerProcesses(organizationId, serverId, minCpu?, minMemory?)',
            'icon' => '⚙️',
        ],
        [
            'name' => 'get_server_services',
            'class' => \App\Mcp\Tools\Server\GetServerServicesTool::class,
            'description' => 'Get status of all services on a server',
            'usage' => 'getServerServices(organizationId, serverId)',
            'icon' => '🔧',
        ],
        [
            'name' => 'update_server_service',
            'class' => \App\Mcp\Tools\Server\UpdateServerServiceTool::class,
            'description' => 'Update (start, stop, restart, reload) a service on the server',
            'usage' => 'updateServerService(organizationId, serverId, service, action)',
            'icon' => '🔄',
        ],
        [
            'name' => 'get_php_fpm_content',
            'class' => \App\Mcp\Tools\Server\GetPhpFpmContentTool::class,
            'description' => 'Read PHP-FPM configuration file content for a specific PHP version (php7.4-fpm to php8.5-fpm).',
            'usage' => 'getPhpFpmContent(organizationId, serverId, service)',
            'icon' => '🐘',
        ],
        [
            'name' => 'install_php_version',
            'class' => \App\Mcp\Tools\Server\InstallPhpVersionTool::class,
            'description' => 'Install a specific PHP version on the server (versions 7.2 to 8.5)',
            'usage' => 'installPhpVersion(organizationId, serverId, version)',
            'icon' => '📦',
        ],
        [
            'name' => 'update_server_general_settings',
            'class' => \App\Mcp\Tools\Server\UpdateServerGeneralSettingsTool::class,
            'description' => 'Update general settings of server (name, hostname, timezone, php_cli_version)',
            'usage' => 'updateServerGeneralSettings(organizationId, serverId, name, hostname, timezone, phpCliVersion?, olsAutoRestart?)',
            'icon' => '⚙️',
        ],
        [
            'name' => 'restart_server',
            'class' => \App\Mcp\Tools\Server\RestartServerTool::class,
            'description' => 'Restart the server (use with caution)',
            'usage' => 'restartServer(organizationId, serverId)',
            'icon' => '🔄',
        ],
        [
            'name' => 'get_server_summary',
            'class' => \App\Mcp\Tools\Server\GetServerSummaryTool::class,
            'description' => 'Get server summary with counts of system users, applications, databases, and cronjobs',
            'usage' => 'getServerSummary(organizationId, serverId)',
            'icon' => '📊',
        ],
        [
            'name' => 'list_organization_applications',
            'class' => \App\Mcp\Tools\Application\ListOrganizationApplicationsTool::class,
            'description' => 'List all applications across all servers in an organization',
            'usage' => 'listOrganizationApplications(organizationId)',
            'icon' => '🌍',
        ],
        [
            'name' => 'list_server_applications',
            'class' => \App\Mcp\Tools\Application\ListApplicationsTool::class,
            'description' => 'List all applications (websites) on a specific server',
            'usage' => 'listServerApplications(organizationId, serverId)',
            'icon' => '🌐',
        ],
        [
            'name' => 'get_application',
            'class' => \App\Mcp\Tools\Application\GetApplicationTool::class,
            'description' => 'Get details of a specific application (website)',
            'usage' => 'getApplication(organizationId, serverId, applicationId)',
            'icon' => '🔍',
        ],
        [
            'name' => 'create_application',
            'class' => \App\Mcp\Tools\Application\CreateApplicationTool::class,
            'description' => 'Create a new application (website) on a server',
            'usage' => 'createApplication(organizationId, serverId, name, framework, ...)',
            'icon' => '➕',
        ],
        [
            'name' => 'delete_application',
            'class' => \App\Mcp\Tools\Application\DeleteApplicationTool::class,
            'description' => 'Delete a specific application (website) from a server',
            'usage' => 'deleteApplication(organizationId, serverId, applicationId)',
            'icon' => '🗑️',
        ],
        [
            'name' => 'toggle_application',
            'class' => \App\Mcp\Tools\Application\ToggleApplicationTool::class,
            'description' => 'Enable or disable an application on a server',
            'usage' => 'toggleApplication(organizationId, serverId, applicationId)',
            'icon' => '🔄',
        ],
        [
            'name' => 'update_php_settings',
            'class' => \App\Mcp\Tools\Application\UpdatePhpSettingsTool::class,
            'description' => 'Update PHP configuration for an application',
            'usage' => 'updatePhpSettings(organizationId, serverId, applicationId, ...)',
            'icon' => '🐘',
        ],
        [
            'name' => 'manage_basic_auth',
            'class' => \App\Mcp\Tools\Application\ManageBasicAuthTool::class,
            'description' => 'Get, create, or disable basic authentication for an application',
            'usage' => 'manageBasicAuth(organizationId, serverId, applicationId, action, username?, password?)',
            'icon' => '🔐',
        ],
        [
            'name' => 'list_databases',
            'class' => \App\Mcp\Tools\Database\ListDatabasesTool::class,
            'description' => 'List all databases',
            'usage' => 'listDatabases(organizationId)',
            'icon' => '🗄️',
        ],
        [
            'name' => 'get_database',
            'class' => \App\Mcp\Tools\Database\GetDatabaseTool::class,
            'description' => 'Get details of a specific database',
            'usage' => 'getDatabase(organizationId, databaseId)',
            'icon' => '💾',
        ],
        [
            'name' => 'list_backups',
            'class' => \App\Mcp\Tools\Backup\ListBackupsTool::class,
            'description' => 'List all backups',
            'usage' => 'listBackups(organizationId)',
            'icon' => '☁️',
        ],
    ],
];
