<?php

return [
    'tools' => [
        [
            'name' => 'create_organization',
            'class' => \App\Mcp\Tools\Organization\CreateOrganizationTool::class,
            'description' => 'Create a new organization in ServerAvatar',
            'usage' => 'createOrganization(name, description?)',
            'icon' => 'fa-building',
        ],
        [
            'name' => 'list_organizations',
            'class' => \App\Mcp\Tools\Organization\ListOrganizationsTool::class,
            'description' => 'List all organizations in your ServerAvatar account',
            'usage' => 'listOrganizations()',
            'icon' => 'fa-building',
        ],
        [
            'name' => 'get_organization',
            'class' => \App\Mcp\Tools\Organization\GetOrganizationTool::class,
            'description' => 'Get details of a specific organization by its ID',
            'usage' => 'getOrganization(organizationId)',
            'icon' => 'fa-building',
        ],
        [
            'name' => 'delete_server',
            'class' => \App\Mcp\Tools\Server\DeleteServerTool::class,
            'description' => 'Delete/destroy a server (WARNING: cannot reconnect without support)',
            'usage' => 'destroyServer(organizationId, serverId, deleteFromProvider?)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'list_cloud_provider_sizes',
            'class' => \App\Mcp\Tools\Server\ListCloudProviderSizesTool::class,
            'description' => 'Get available server instance sizes for a cloud provider and region',
            'usage' => 'listCloudProviderSizes(organizationId, cloudServerProviderId, region)',
            'icon' => 'fa-box',
        ],
        [
            'name' => 'list_cloud_provider_regions',
            'class' => \App\Mcp\Tools\Server\ListCloudProviderRegionsTool::class,
            'description' => 'Get available regions for a cloud server provider',
            'usage' => 'listCloudProviderRegions(organizationId, cloudServerProviderId)',
            'icon' => 'fa-globe',
        ],
        [
            'name' => 'list_cloud_server_providers',
            'class' => \App\Mcp\Tools\Server\ListCloudServerProvidersTool::class,
            'description' => 'Get list of connected cloud server providers (AWS, DigitalOcean, Vultr, Linode, Hetzner)',
            'usage' => 'listCloudServerProviders(organizationId, provider?, search?, page?)',
            'icon' => 'fa-cloud',
        ],
        [
            'name' => 'create_server',
            'class' => \App\Mcp\Tools\Server\CreateServerTool::class,
            'description' => 'Create a new server (direct with root password or via provider: AWS, DigitalOcean, Vultr, Linode, Hetzner)',
            'usage' => 'createServer(organizationId, name, webServer, databaseType, nodejs, provider?, ...)',
            'icon' => 'fa-desktop',
        ],
        [
            'name' => 'list_servers',
            'class' => \App\Mcp\Tools\Server\ListServersTool::class,
            'description' => 'List all servers in your ServerAvatar account',
            'usage' => 'listServers(organizationId)',
            'icon' => 'fa-desktop',
        ],
        [
            'name' => 'list_server_databases',
            'class' => \App\Mcp\Tools\Database\ListServerDatabasesTool::class,
            'description' => 'List all databases on a specific server',
            'usage' => 'listServerDatabases(organizationId, serverId)',
            'icon' => 'fa-database',
        ],
        [
            'name' => 'list_organization_databases',
            'class' => \App\Mcp\Tools\Database\ListOrganizationDatabasesTool::class,
            'description' => 'List all databases within an organization',
            'usage' => 'listOrganizationDatabases(organizationId)',
            'icon' => 'fa-database',
        ],
        [
            'name' => 'create_database',
            'class' => \App\Mcp\Tools\Database\CreateDatabaseTool::class,
            'description' => 'Create a new database on a server',
            'usage' => 'createDatabase(organizationId, serverId, name, username, password, connectionPreference?, hostname?)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'delete_database',
            'class' => \App\Mcp\Tools\Database\DeleteDatabaseTool::class,
            'description' => 'Delete a database from a server',
            'usage' => 'deleteDatabase(organizationId, serverId, databaseId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'list_database_users',
            'class' => \App\Mcp\Tools\DatabaseUser\ListDatabaseUsersTool::class,
            'description' => 'List all database users for a specific database',
            'usage' => 'listDatabaseUsers(organizationId, serverId, databaseId)',
            'icon' => 'fa-users',
        ],
        [
            'name' => 'create_database_user',
            'class' => \App\Mcp\Tools\DatabaseUser\CreateDatabaseUserTool::class,
            'description' => 'Create a new database user for a database',
            'usage' => 'createDatabaseUser(organizationId, serverId, databaseId, username, password, connectionPreference?, hostname?)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'update_database_user',
            'class' => \App\Mcp\Tools\DatabaseUser\UpdateDatabaseUserTool::class,
            'description' => 'Update an existing database user',
            'usage' => 'updateDatabaseUser(organizationId, serverId, databaseId, databaseUserId, username, password, connectionPreference?, hostname?)',
            'icon' => 'fa-pencil',
        ],
        [
            'name' => 'delete_database_user',
            'class' => \App\Mcp\Tools\DatabaseUser\DeleteDatabaseUserTool::class,
            'description' => 'Delete database users from a database',
            'usage' => 'deleteDatabaseUser(organizationId, serverId, databaseId, ids)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'get_server',
            'class' => \App\Mcp\Tools\Server\GetServerTool::class,
            'description' => 'Get details of a specific server',
            'usage' => 'getServer(organizationId, serverId)',
            'icon' => 'fa-chart-bar',
        ],
        [
            'name' => 'get_server_usage',
            'class' => \App\Mcp\Tools\Server\GetServerUsageTool::class,
            'description' => 'Get CPU, Memory, and Disk usage for a server',
            'usage' => 'getServerUsage(organizationId, serverId)',
            'icon' => 'fa-chart-line',
        ],
        [
            'name' => 'view_server_logs',
            'class' => \App\Mcp\Tools\Server\ViewServerLogsTool::class,
            'description' => 'View server logs',
            'usage' => 'viewServerLogs(organizationId, serverId)',
            'icon' => 'fa-clipboard-list',
        ],
        [
            'name' => 'get_server_processes',
            'class' => \App\Mcp\Tools\Server\GetServerProcessesTool::class,
            'description' => 'Get list of running processes on a server',
            'usage' => 'getServerProcesses(organizationId, serverId, minCpu?, minMemory?)',
            'icon' => 'fa-gear',
        ],
        [
            'name' => 'get_server_services',
            'class' => \App\Mcp\Tools\Server\GetServerServicesTool::class,
            'description' => 'Get status of all services on a server',
            'usage' => 'getServerServices(organizationId, serverId)',
            'icon' => 'fa-wrench',
        ],
        [
            'name' => 'update_server_service',
            'class' => \App\Mcp\Tools\Server\UpdateServerServiceTool::class,
            'description' => 'Update (start, stop, restart, reload) a service on the server',
            'usage' => 'updateServerService(organizationId, serverId, service, action)',
            'icon' => 'fa-refresh',
        ],
        [
            'name' => 'get_php_fpm_content',
            'class' => \App\Mcp\Tools\Server\GetPhpFpmContentTool::class,
            'description' => 'Read PHP-FPM configuration file content for a specific PHP version (php7.4-fpm to php8.5-fpm).',
            'usage' => 'getPhpFpmContent(organizationId, serverId, service)',
            'icon' => 'fa-database',
        ],
        [
            'name' => 'install_php_version',
            'class' => \App\Mcp\Tools\Server\InstallPhpVersionTool::class,
            'description' => 'Install a specific PHP version on the server (versions 7.2 to 8.5)',
            'usage' => 'installPhpVersion(organizationId, serverId, version)',
            'icon' => 'fa-box',
        ],
        [
            'name' => 'update_server_general_settings',
            'class' => \App\Mcp\Tools\Server\UpdateServerGeneralSettingsTool::class,
            'description' => 'Update general settings of server (name, hostname, timezone, php_cli_version)',
            'usage' => 'updateServerGeneralSettings(organizationId, serverId, name, hostname, timezone, phpCliVersion?, olsAutoRestart?)',
            'icon' => 'fa-gear',
        ],
        [
            'name' => 'restart_server',
            'class' => \App\Mcp\Tools\Server\RestartServerTool::class,
            'description' => 'Restart the server (use with caution)',
            'usage' => 'restartServer(organizationId, serverId)',
            'icon' => 'fa-refresh',
        ],
        [
            'name' => 'set_server_restart_schedule',
            'class' => \App\Mcp\Tools\Server\SetServerRestartScheduleTool::class,
            'description' => 'Set the server restart schedule (daily, weekly, monthly, or specific_hour with hour in UTC)',
            'usage' => 'setServerRestartSchedule(organizationId, serverId, restartSchedule, restartHour?)',
            'icon' => 'fa-clock',
        ],
        [
            'name' => 'update_server_tags',
            'class' => \App\Mcp\Tools\Server\UpdateServerTagsTool::class,
            'description' => 'Update (replace) all tags for a server. Provide an array of tag names (strings). Example: tags=["Production", "Backend"]',
            'usage' => 'updateServerTags(organizationId, serverId, tags)',
            'icon' => 'fa-tag',
        ],
        [
            'name' => 'delete_server_tags',
            'class' => \App\Mcp\Tools\Server\DeleteServerTagsTool::class,
            'description' => 'Delete all tags from a server',
            'usage' => 'deleteServerTags(organizationId, serverId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'list_server_alerts',
            'class' => \App\Mcp\Tools\Server\ListServerAlertsTool::class,
            'description' => 'List server alerts configuration (server load, memory, disk thresholds)',
            'usage' => 'listServerAlerts(organizationId, serverId)',
            'icon' => 'fa-bell',
        ],
        [
            'name' => 'update_server_alerts',
            'class' => \App\Mcp\Tools\Server\UpdateServerAlertsTool::class,
            'description' => 'Update server alerts configuration (thresholds for server load, memory, disk)',
            'usage' => 'updateServerAlerts(organizationId, serverId, serverLoad, memoryUsage, diskUsage, ...)',
            'icon' => 'fa-bell',
        ],
        [
            'name' => 'toggle_server_firewall',
            'class' => \App\Mcp\Tools\Firewall\ToggleServerFirewallTool::class,
            'description' => 'Toggle the server firewall (enable or disable the firewall)',
            'usage' => 'toggleServerFirewall(organizationId, serverId)',
            'icon' => 'fa-fire',
        ],
        [
            'name' => 'list_firewall_rules',
            'class' => \App\Mcp\Tools\Firewall\ListFirewallRulesTool::class,
            'description' => 'List all firewall rules for a server (firewall must be enabled first)',
            'usage' => 'listFirewallRules(organizationId, serverId)',
            'icon' => 'fa-clipboard-list',
        ],
        [
            'name' => 'create_firewall_rule',
            'class' => \App\Mcp\Tools\Firewall\CreateFirewallRuleTool::class,
            'description' => 'Create a new firewall rule for a server (start_port, traffic: allow/deny, protocol: all/tcp/udp, optional: end_port, ip, description)',
            'usage' => 'createFirewallRule(organizationId, serverId, startPort, traffic, protocol, endPort?, ip?, description?)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'delete_firewall_rule',
            'class' => \App\Mcp\Tools\Firewall\DeleteFirewallRuleTool::class,
            'description' => 'Delete a firewall rule from a server (requires firewall_rule_id from listFirewallRules)',
            'usage' => 'deleteFirewallRule(organizationId, serverId, firewallRuleId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'create_cronjob',
            'class' => \App\Mcp\Tools\Cronjob\CreateCronjobTool::class,
            'description' => 'Create a new cronjob for a server (preset schedules: everyMinute to everyMonth, or custom with minute/hour/month/day_of_week/day_of_month)',
            'usage' => 'createCronjob(organizationId, serverId, name, command, schedule, systemUser, customFields?)',
            'icon' => 'fa-clock',
        ],
        [
            'name' => 'list_cronjobs',
            'class' => \App\Mcp\Tools\Cronjob\ListCronjobsTool::class,
            'description' => 'List all cronjobs for a server (shows name, command, schedule, system_user, enabled status)',
            'usage' => 'listCronjobs(organizationId, serverId)',
            'icon' => 'fa-clipboard-list',
        ],
        [
            'name' => 'get_cronjob',
            'class' => \App\Mcp\Tools\Cronjob\GetCronjobTool::class,
            'description' => 'Get details of a specific cronjob (schedule, system_user, enabled, custom scheduling fields)',
            'usage' => 'getCronjob(organizationId, serverId, cronjobId)',
            'icon' => 'fa-magnifying-glass',
        ],
        [
            'name' => 'update_cronjob',
            'class' => \App\Mcp\Tools\Cronjob\UpdateCronjobTool::class,
            'description' => 'Update an existing cronjob (command, schedule, system_user required, custom fields optional)',
            'usage' => 'updateCronjob(organizationId, serverId, cronjobId, command, schedule, systemUser)',
            'icon' => 'fa-pencil',
        ],
        [
            'name' => 'toggle_cronjob',
            'class' => \App\Mcp\Tools\Cronjob\ToggleCronjobTool::class,
            'description' => 'Enable or disable a cronjob (toggles current state)',
            'usage' => 'toggleCronjob(organizationId, serverId, cronjobId)',
            'icon' => 'fa-refresh',
        ],
        [
            'name' => 'delete_cronjob',
            'class' => \App\Mcp\Tools\Cronjob\DeleteCronjobTool::class,
            'description' => 'Delete a cronjob from a server (requires cronjob_id from listCronjobs)',
            'usage' => 'deleteCronjob(organizationId, serverId, cronjobId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'list_users',
            'class' => \App\Mcp\Tools\ApplicationUser\ListUsersTool::class,
            'description' => 'List all application users for a server (username, ssh_access, root_access, applications)',
            'usage' => 'listUsers(organizationId, serverId)',
            'icon' => 'fa-users',
        ],
        [
            'name' => 'create_user',
            'class' => \App\Mcp\Tools\ApplicationUser\CreateUserTool::class,
            'description' => 'Create a new application user (username, password + confirmation, optional public_key)',
            'usage' => 'createUser(organizationId, serverId, username, password, passwordConfirmation, publicKey?)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'get_user',
            'class' => \App\Mcp\Tools\ApplicationUser\GetUserTool::class,
            'description' => 'Get details of a specific application user (username, ssh_access, root_access)',
            'usage' => 'getUser(organizationId, serverId, systemUserId)',
            'icon' => 'fa-magnifying-glass',
        ],
        [
            'name' => 'update_user',
            'class' => \App\Mcp\Tools\ApplicationUser\UpdateUserTool::class,
            'description' => 'Update application user: type=password (new password + confirmation) or type=key (public_key)',
            'usage' => 'updateUser(organizationId, serverId, systemUserId, type, password?, passwordConfirmation?, publicKey?)',
            'icon' => 'fa-pencil',
        ],
        [
            'name' => 'delete_user',
            'class' => \App\Mcp\Tools\ApplicationUser\DeleteUserTool::class,
            'description' => 'Delete application users (array of IDs from listUsers). Cannot delete users with associated applications.',
            'usage' => 'deleteUser(organizationId, serverId, ids)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'toggle_user_ssh_access',
            'class' => \App\Mcp\Tools\ApplicationUser\ToggleUserSshAccessTool::class,
            'description' => 'Enable or disable SFTP/SSH access for an application user (toggles current state)',
            'usage' => 'toggleUserSshAccess(organizationId, serverId, systemUserId)',
            'icon' => 'fa-lock',
        ],
        [
            'name' => 'toggle_user_root_access',
            'class' => \App\Mcp\Tools\ApplicationUser\ToggleUserRootAccessTool::class,
            'description' => 'Enable or disable SSH root access for an application user (action: "enable" or "disable")',
            'usage' => 'toggleUserRootAccess(organizationId, serverId, systemUserId, action)',
            'icon' => 'fa-key',
        ],
        [
            'name' => 'remove_user_ssh_key',
            'class' => \App\Mcp\Tools\ApplicationUser\RemoveUserSshKeyTool::class,
            'description' => 'Remove the SSH key for an application user',
            'usage' => 'removeUserSshKey(organizationId, serverId, systemUserId)',
            'icon' => 'fa-lock',
        ],
        [
            'name' => 'get_server_summary',
            'class' => \App\Mcp\Tools\Server\GetServerSummaryTool::class,
            'description' => 'Get server summary with counts of system users, applications, databases, and cronjobs',
            'usage' => 'getServerSummary(organizationId, serverId)',
            'icon' => 'fa-chart-bar',
        ],
        [
            'name' => 'list_organization_applications',
            'class' => \App\Mcp\Tools\Application\ListOrganizationApplicationsTool::class,
            'description' => 'List all applications across all servers in an organization',
            'usage' => 'listOrganizationApplications(organizationId)',
            'icon' => 'fa-globe',
        ],
        [
            'name' => 'list_server_applications',
            'class' => \App\Mcp\Tools\Application\ListApplicationsTool::class,
            'description' => 'List all applications (websites) on a specific server',
            'usage' => 'listServerApplications(organizationId, serverId)',
            'icon' => 'fa-globe',
        ],
        [
            'name' => 'get_application',
            'class' => \App\Mcp\Tools\Application\GetApplicationTool::class,
            'description' => 'Get details of a specific application (website)',
            'usage' => 'getApplication(organizationId, serverId, applicationId)',
            'icon' => 'fa-magnifying-glass',
        ],
        [
            'name' => 'create_application',
            'class' => \App\Mcp\Tools\Application\CreateApplicationTool::class,
            'description' => 'Create a new application (website) on a server',
            'usage' => 'createApplication(organizationId, serverId, name, framework, ...)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'create_node_application',
            'class' => \App\Mcp\Tools\Application\Node\CreateNodeApplicationTool::class,
            'description' => 'Create a new Node.js one-click application (UptimeKuma, Node-RED, N8N, NodeBB)',
            'usage' => 'createNodeApplication(organizationId, serverId, name, framework, packageManager, processMode, ...)',
            'icon' => 'fa-circle-notch',
        ],
        [
            'name' => 'get_node_deployment',
            'class' => \App\Mcp\Tools\Application\Node\GetNodeDeploymentTool::class,
            'description' => 'Get Node.js deployment details for an application (rendering, build command, port, env variables, nginx config)',
            'usage' => 'getNodeDeployment(organizationId, serverId, applicationId)',
            'icon' => 'fa-clipboard-list',
        ],
        [
            'name' => 'update_ssr_port',
            'class' => \App\Mcp\Tools\Application\Node\UpdateSsrPortTool::class,
            'description' => 'Update SSR port for a Node.js application on a Node Stack server',
            'usage' => 'updateSsrPort(organizationId, serverId, applicationId, port)',
            'icon' => 'fa-plug',
        ],
        [
            'name' => 'get_pm2_detail',
            'class' => \App\Mcp\Tools\Application\Node\GetPm2DetailTool::class,
            'description' => 'Get PM2 process details for a Node.js application (PID, status, memory, CPU, uptime)',
            'usage' => 'getPm2Detail(organizationId, serverId, applicationId)',
            'icon' => 'fa-chart-bar',
        ],
        [
            'name' => 'get_pm2_log',
            'class' => \App\Mcp\Tools\Application\Node\GetPm2LogTool::class,
            'description' => 'Get PM2 log for a Node.js application (file: error or out, optional tail lines)',
            'usage' => 'getPm2Log(organizationId, serverId, applicationId, file, selectTailLines?, numberOfTailLines?)',
            'icon' => 'fa-file-lines',
        ],
        [
            'name' => 'delete_application',
            'class' => \App\Mcp\Tools\Application\DeleteApplicationTool::class,
            'description' => 'Delete a specific application (website) from a server',
            'usage' => 'deleteApplication(organizationId, serverId, applicationId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'toggle_application',
            'class' => \App\Mcp\Tools\Application\ToggleApplicationTool::class,
            'description' => 'Enable or disable an application on a server',
            'usage' => 'toggleApplication(organizationId, serverId, applicationId)',
            'icon' => 'fa-refresh',
        ],
        [
            'name' => 'update_php_settings',
            'class' => \App\Mcp\Tools\Application\UpdatePhpSettingsTool::class,
            'description' => 'Update PHP configuration for an application',
            'usage' => 'updatePhpSettings(organizationId, serverId, applicationId, ...)',
            'icon' => 'fa-database',
        ],
        [
            'name' => 'manage_basic_auth',
            'class' => \App\Mcp\Tools\Application\ManageBasicAuthTool::class,
            'description' => 'Get, create, or disable basic authentication for an application',
            'usage' => 'manageBasicAuth(organizationId, serverId, applicationId, action, username?, password?)',
            'icon' => 'fa-lock',
        ],
        [
            'name' => 'toggle_8g_firewall',
            'class' => \App\Mcp\Tools\Application\Toggle8gFirewallTool::class,
            'description' => 'Enable or disable the 8G Firewall on an application',
            'usage' => 'toggle8gFirewall(organizationId, serverId, applicationId, enabled)',
            'icon' => 'fa-shield',
        ],
        [
            'name' => 'list_supervisors',
            'class' => \App\Mcp\Tools\Supervisor\ListSupervisorsTool::class,
            'description' => 'List all supervisors (process managers) for an application. Shows name, user, command, autostart, autorestart, numprocs, logfile, and loglevel for queue workers or background tasks.',
            'usage' => 'listSupervisors(organizationId, serverId, applicationId)',
            'icon' => 'fa-gear',
        ],
        [
            'name' => 'get_supervisor',
            'class' => \App\Mcp\Tools\Supervisor\GetSupervisorTool::class,
            'description' => 'Get details of a specific supervisor by ID. Returns name, user, command, autostart, autorestart, numprocs, logfile, and loglevel.',
            'usage' => 'getSupervisor(organizationId, serverId, applicationId, supervisorId)',
            'icon' => 'fa-eye',
        ],
        [
            'name' => 'create_supervisor',
            'class' => \App\Mcp\Tools\Supervisor\CreateSupervisorTool::class,
            'description' => 'Create a new supervisor (process manager) for an application. Configure queue workers with autostart, autorestart, numprocs, log level, and more.',
            'usage' => 'createSupervisor(organizationId, serverId, applicationId, name, command, autostart, autorestart, numprocs, user, logfile, loglevel)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'update_supervisor',
            'class' => \App\Mcp\Tools\Supervisor\UpdateSupervisorTool::class,
            'description' => 'Update an existing supervisor configuration. Change name, command, autostart, autorestart, numprocs, log level, and more.',
            'usage' => 'updateSupervisor(organizationId, serverId, applicationId, supervisorId, name, command, autostart, autorestart, numprocs, user, logfile, loglevel)',
            'icon' => 'fa-pencil',
        ],
        [
            'name' => 'delete_supervisor',
            'class' => \App\Mcp\Tools\Supervisor\DeleteSupervisorTool::class,
            'description' => 'Delete a supervisor (process manager) from an application. This will stop the supervised process.',
            'usage' => 'deleteSupervisor(organizationId, serverId, applicationId, supervisorId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'list_domains',
            'class' => \App\Mcp\Tools\ApplicationDomain\ListDomainsTool::class,
            'description' => 'List all domain names for an application',
            'usage' => 'listDomains(organizationId, serverId, applicationId)',
            'icon' => 'fa-globe',
        ],
        [
            'name' => 'create_domain',
            'class' => \App\Mcp\Tools\ApplicationDomain\CreateDomainTool::class,
            'description' => 'Create a new domain/subdomain for an application',
            'usage' => 'createDomain(organizationId, serverId, applicationId, domain)',
            'icon' => 'fa-plus',
        ],
        [
            'name' => 'delete_domain',
            'class' => \App\Mcp\Tools\ApplicationDomain\DeleteDomainTool::class,
            'description' => 'Delete an application domain (primary domain cannot be deleted)',
            'usage' => 'deleteDomain(organizationId, serverId, applicationId, domainId)',
            'icon' => 'fa-trash',
        ],
        [
            'name' => 'change_primary_domain',
            'class' => \App\Mcp\Tools\ApplicationDomain\ChangePrimaryDomainTool::class,
            'description' => 'Change the primary domain of an application',
            'usage' => 'changePrimaryDomain(organizationId, serverId, applicationId, domainId, isWordpressUrlUpdate)',
            'icon' => 'fa-star',
        ],
        [
            'name' => 'toggle_domain',
            'class' => \App\Mcp\Tools\ApplicationDomain\ToggleDomainTool::class,
            'description' => 'Enable or disable an application domain',
            'usage' => 'toggleDomain(organizationId, serverId, applicationId, domainId)',
            'icon' => 'fa-circle-dot',
        ],
        [
            'name' => 'list_backups',
            'class' => \App\Mcp\Tools\Backup\ListBackupsTool::class,
            'description' => 'List all backups',
            'usage' => 'listBackups(organizationId)',
            'icon' => 'fa-cloud',
        ],
        [
            'name' => 'get_ssl_certificate',
            'class' => \App\Mcp\Tools\SSL\GetSslCertificateTool::class,
            'description' => 'Get SSL certificate details for an application (issuer, domains, expiry, validity)',
            'usage' => 'getSslCertificate(organizationId, serverId, applicationId)',
            'icon' => 'fa-lock',
        ],
        [
            'name' => 'install_ssl_certificate',
            'class' => \App\Mcp\Tools\SSL\InstallSslCertificateTool::class,
            'description' => "Install SSL certificate (automatic for Let's Encrypt, or custom with certificate files)",
            'usage' => 'installSslCertificate(organizationId, serverId, applicationId, sslType, forceHttps, ...)',
            'icon' => 'fa-lock',
        ],
        [
            'name' => 'update_ssl_certificate',
            'class' => \App\Mcp\Tools\SSL\UpdateSslCertificateTool::class,
            'description' => 'Update a custom SSL certificate (requires ssl_certificate and private_key)',
            'usage' => 'updateSslCertificate(organizationId, serverId, applicationId, sslCertificate, privateKey, chainFile?)',
            'icon' => 'fa-refresh',
        ],
        [
            'name' => 'uninstall_ssl_certificate',
            'class' => \App\Mcp\Tools\SSL\UninstallSslCertificateTool::class,
            'description' => 'Uninstall/remove SSL certificate from an application',
            'usage' => 'uninstallSslCertificate(organizationId, serverId, applicationId)',
            'icon' => 'fa-times',
        ],
        [
            'name' => 'force_https',
            'class' => \App\Mcp\Tools\SSL\ForceHttpsTool::class,
            'description' => 'Enable HTTP to HTTPS redirection',
            'usage' => 'forceHttps(organizationId, serverId, applicationId)',
            'icon' => 'fa-rotate-right',
        ],
        [
            'name' => 'stop_force_https',
            'class' => \App\Mcp\Tools\SSL\StopForceHttpsTool::class,
            'description' => 'Disable HTTP to HTTPS redirection',
            'usage' => 'stopForceHttps(organizationId, serverId, applicationId)',
            'icon' => 'fa-stop',
        ],

        // WordPress Toolkit - Summary
        [
            'name' => 'get_wordpress_summary',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressSummaryTool::class,
            'description' => 'Get WordPress Toolkit summary (core version, maintenance, plugin/theme counts)',
            'usage' => 'getWordpressSummary(organizationId, serverId, applicationId)',
            'icon' => 'fa-chart-pie',
        ],
        [
            'name' => 'get_wordpress_user_summary',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressUserSummaryTool::class,
            'description' => 'Get WordPress user summary (user counts)',
            'usage' => 'getWordpressUserSummary(organizationId, serverId, applicationId)',
            'icon' => 'fa-users',
        ],
        [
            'name' => 'get_wordpress_theme_summary',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressThemeSummaryTool::class,
            'description' => 'Get WordPress theme summary (theme counts, active theme, updates)',
            'usage' => 'getWordpressThemeSummary(organizationId, serverId, applicationId)',
            'icon' => 'fa-palette',
        ],
        [
            'name' => 'get_wordpress_plugin_summary',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressPluginSummaryTool::class,
            'description' => 'Get WordPress plugin summary (plugin counts, updates)',
            'usage' => 'getWordpressPluginSummary(organizationId, serverId, applicationId)',
            'icon' => 'fa-plug',
        ],
        [
            'name' => 'get_wordpress_cron_summary',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressCronSummaryTool::class,
            'description' => 'Get WordPress cron summary (WP Cron status, server cron configured)',
            'usage' => 'getWordpressCronSummary(organizationId, serverId, applicationId)',
            'icon' => 'fa-clock',
        ],

        // WordPress Toolkit - Core Updates
        [
            'name' => 'update_wordpress_core',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateWordpressCoreTool::class,
            'description' => 'Update WordPress core to latest or specific version',
            'usage' => 'updateWordpressCore(organizationId, serverId, applicationId, version?)',
            'icon' => 'fa-arrows-rotate',
        ],
        [
            'name' => 'update_wordpress_database',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateWordpressDatabaseTool::class,
            'description' => 'Run WordPress database schema upgrade after core update',
            'usage' => 'updateWordpressDatabase(organizationId, serverId, applicationId, dry_run?)',
            'icon' => 'fa-database',
        ],

        // WordPress Toolkit - Themes
        [
            'name' => 'list_wordpress_themes',
            'class' => \App\Mcp\Tools\WordpressToolkit\ListWordpressThemesTool::class,
            'description' => 'List all installed WordPress themes',
            'usage' => 'listWordpressThemes(organizationId, serverId, applicationId)',
            'icon' => 'fa-palette',
        ],
        [
            'name' => 'install_wordpress_theme',
            'class' => \App\Mcp\Tools\WordpressToolkit\InstallWordpressThemeTool::class,
            'description' => 'Install a WordPress theme from WordPress.org',
            'usage' => 'installWordpressTheme(organizationId, serverId, applicationId, theme)',
            'icon' => 'fa-download',
        ],
        [
            'name' => 'update_wordpress_theme',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateWordpressThemeTool::class,
            'description' => 'Update a specific WordPress theme to latest or version',
            'usage' => 'updateWordpressTheme(organizationId, serverId, applicationId, theme, version?)',
            'icon' => 'fa-arrow-up',
        ],
        [
            'name' => 'update_all_wordpress_themes',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateAllWordpressThemesTool::class,
            'description' => 'Update all WordPress themes to latest versions',
            'usage' => 'updateAllWordpressThemes(organizationId, serverId, applicationId)',
            'icon' => 'fa-up-down-left-right',
        ],
        [
            'name' => 'activate_wordpress_theme',
            'class' => \App\Mcp\Tools\WordpressToolkit\ActivateWordpressThemeTool::class,
            'description' => 'Activate a WordPress theme',
            'usage' => 'activateWordpressTheme(organizationId, serverId, applicationId, theme)',
            'icon' => 'fa-check',
        ],
        [
            'name' => 'uninstall_wordpress_theme',
            'class' => \App\Mcp\Tools\WordpressToolkit\UninstallWordpressThemeTool::class,
            'description' => 'Uninstall a WordPress theme (must deactivate first)',
            'usage' => 'uninstallWordpressTheme(organizationId, serverId, applicationId, theme)',
            'icon' => 'fa-trash',
        ],

        // WordPress Toolkit - Plugins
        [
            'name' => 'list_wordpress_plugins',
            'class' => \App\Mcp\Tools\WordpressToolkit\ListWordpressPluginsTool::class,
            'description' => 'List all installed WordPress plugins',
            'usage' => 'listWordpressPlugins(organizationId, serverId, applicationId)',
            'icon' => 'fa-plug',
        ],
        [
            'name' => 'install_wordpress_plugin',
            'class' => \App\Mcp\Tools\WordpressToolkit\InstallWordpressPluginTool::class,
            'description' => 'Install a WordPress plugin from WordPress.org',
            'usage' => 'installWordpressPlugin(organizationId, serverId, applicationId, plugin)',
            'icon' => 'fa-download',
        ],
        [
            'name' => 'update_wordpress_plugin',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateWordpressPluginTool::class,
            'description' => 'Update a specific WordPress plugin to latest or version',
            'usage' => 'updateWordpressPlugin(organizationId, serverId, applicationId, plugin, version?)',
            'icon' => 'fa-arrow-up',
        ],
        [
            'name' => 'update_all_wordpress_plugins',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateAllWordpressPluginsTool::class,
            'description' => 'Update all WordPress plugins to latest versions',
            'usage' => 'updateAllWordpressPlugins(organizationId, serverId, applicationId)',
            'icon' => 'fa-up-down-left-right',
        ],
        [
            'name' => 'toggle_wordpress_plugin',
            'class' => \App\Mcp\Tools\WordpressToolkit\ToggleWordpressPluginTool::class,
            'description' => 'Activate or deactivate a WordPress plugin',
            'usage' => 'toggleWordpressPlugin(organizationId, serverId, applicationId, plugin, action)',
            'icon' => 'fa-toggle-on',
        ],
        [
            'name' => 'uninstall_wordpress_plugin',
            'class' => \App\Mcp\Tools\WordpressToolkit\UninstallWordpressPluginTool::class,
            'description' => 'Uninstall a WordPress plugin (must deactivate first)',
            'usage' => 'uninstallWordpressPlugin(organizationId, serverId, applicationId, plugin)',
            'icon' => 'fa-trash',
        ],

        // WordPress Toolkit - Performance
        [
            'name' => 'flush_wordpress_rewrite_rules',
            'class' => \App\Mcp\Tools\WordpressToolkit\FlushWordpressRewriteRulesTool::class,
            'description' => 'Regenerate WordPress permalink rewrite rules',
            'usage' => 'flushWordpressRewriteRules(organizationId, serverId, applicationId)',
            'icon' => 'fa-rotate',
        ],
        [
            'name' => 'flush_wordpress_cache',
            'class' => \App\Mcp\Tools\WordpressToolkit\FlushWordpressCacheTool::class,
            'description' => 'Flush WordPress object/page cache',
            'usage' => 'flushWordpressCache(organizationId, serverId, applicationId)',
            'icon' => 'fa-bolt',
        ],

        // WordPress Toolkit - Cron
        [
            'name' => 'set_wordpress_cron_mode',
            'class' => \App\Mcp\Tools\WordpressToolkit\SetWordpressCronModeTool::class,
            'description' => 'Set WordPress cron mode (wp_cron or server_cron)',
            'usage' => 'setWordpressCronMode(organizationId, serverId, applicationId, mode)',
            'icon' => 'fa-clock',
        ],
        [
            'name' => 'run_wordpress_cron',
            'class' => \App\Mcp\Tools\WordpressToolkit\RunWordpressCronTool::class,
            'description' => 'Run WordPress cron events manually',
            'usage' => 'runWordpressCron(organizationId, serverId, applicationId, run_all?)',
            'icon' => 'fa-play',
        ],

        // WordPress Toolkit - Security
        [
            'name' => 'toggle_wordpress_xmlrpc',
            'class' => \App\Mcp\Tools\WordpressToolkit\ToggleWordpressXmlrpcTool::class,
            'description' => 'Block or allow XML-RPC access',
            'usage' => 'toggleWordpressXmlrpc(organizationId, serverId, applicationId, action)',
            'icon' => 'fa-shield-halved',
        ],
        [
            'name' => 'toggle_wordpress_php_execution',
            'class' => \App\Mcp\Tools\WordpressToolkit\ToggleWordpressPhpExecutionTool::class,
            'description' => 'Block or allow PHP execution in uploads directory',
            'usage' => 'toggleWordpressPhpExecution(organizationId, serverId, applicationId, action)',
            'icon' => 'fa-code',
        ],
        [
            'name' => 'verify_wordpress_checksums',
            'class' => \App\Mcp\Tools\WordpressToolkit\VerifyWordpressChecksumsTool::class,
            'description' => 'Verify WordPress core files against official checksums',
            'usage' => 'verifyWordpressChecksums(organizationId, serverId, applicationId)',
            'icon' => 'fa-check-double',
        ],

        // WordPress Toolkit - Debug
        [
            'name' => 'get_wordpress_debug_info',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressDebugInfoTool::class,
            'description' => 'Get WordPress debug settings (WP_DEBUG, WP_DEBUG_LOG, WP_DEBUG_DISPLAY)',
            'usage' => 'getWordpressDebugInfo(organizationId, serverId, applicationId)',
            'icon' => 'fa-bug',
        ],
        [
            'name' => 'update_wordpress_debug',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateWordpressDebugTool::class,
            'description' => 'Update WordPress debug setting',
            'usage' => 'updateWordpressDebug(organizationId, serverId, applicationId, setting, value)',
            'icon' => 'fa-screwdriver-wrench',
        ],

        // WordPress Toolkit - Site Settings
        [
            'name' => 'get_wordpress_site_settings',
            'class' => \App\Mcp\Tools\WordpressToolkit\GetWordpressSiteSettingsTool::class,
            'description' => 'Get WordPress site settings (language, timezone, formats, permalinks)',
            'usage' => 'getWordpressSiteSettings(organizationId, serverId, applicationId)',
            'icon' => 'fa-gear',
        ],
        [
            'name' => 'update_wordpress_site_settings',
            'class' => \App\Mcp\Tools\WordpressToolkit\UpdateWordpressSiteSettingsTool::class,
            'description' => 'Update WordPress site settings',
            'usage' => 'updateWordpressSiteSettings(organizationId, serverId, applicationId, ...)',
            'icon' => 'fa-sliders',
        ],

        // WordPress Toolkit - Other
        [
            'name' => 'wordpress_search_replace',
            'class' => \App\Mcp\Tools\WordpressToolkit\WordpressSearchReplaceTool::class,
            'description' => 'Run database search and replace (for URL changes)',
            'usage' => 'wordpressSearchReplace(organizationId, serverId, applicationId, search, replace, dry_run?)',
            'icon' => 'fa-magnifying-glass',
        ],
        [
            'name' => 'enable_wordpress_object_cache_pro',
            'class' => \App\Mcp\Tools\WordpressToolkit\EnableWordpressObjectCacheProTool::class,
            'description' => 'Enable Redis Object Cache Pro for WordPress',
            'usage' => 'enableWordpressObjectCachePro(organizationId, serverId, applicationId, license_key)',
            'icon' => 'fa-database',
        ],
        [
            'name' => 'disable_wordpress_object_cache_pro',
            'class' => \App\Mcp\Tools\WordpressToolkit\DisableWordpressObjectCacheProTool::class,
            'description' => 'Disable Object Cache Pro and remove Redis configuration',
            'usage' => 'disableWordpressObjectCachePro(organizationId, serverId, applicationId)',
            'icon' => 'fa-power-off',
        ],
    ],
];
